Repository alcionai/clues, pull requests merged in 2025-04, with the labels that each got.

#141 allow noop initiation of stats
  ctats/consts.go
  ctats/counter.go
  ctats/counter_test.go
  ctats/ctats.go
  ctats/ctats_test.go
  ctats/gauge.go
  ctats/gauge_test.go
  ctats/histogram.go
  ctats/histogram_test.go
  go.mod
Labels: cleanup

#143 Bump go 1.24
  clues_test.go
  ctats/bus.go
  go.mod
  go.sum
Labels: go

#148 log otel baggage in the context
  clog/builder.go
Labels: enhancement

#152 Fix bug with reinitializing OTEL logger
  clog/builder.go
  clog/logger.go
Labels: bug
